import js from "@eslint/js";
import globals from "globals";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
  globalIgnores([
    // Claude Code agent worktrees are full copies of the repo.
    ".claude/worktrees/**",
    // Generated by pnpm build:cli.
    ".tokens-per-ticket/**",
    "registry/node_modules/**",
  ]),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  { languageOptions: { globals: { ...globals.node } } },
]);
