/**
 * Builds the tokens-per-ticket CLI into one file with no dependencies:
 * .tokens-per-ticket/tpt.mjs. Adopting repos commit that file, so their
 * hooks run in any clone or fresh worktree with nothing but Node installed.
 */
import { readFileSync } from "node:fs";
import { build } from "esbuild";

await build({
  entryPoints: ["src/cli/tpt.ts"],
  outfile: ".tokens-per-ticket/tpt.mjs",
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  legalComments: "none",
  minify: true,
  banner: {
    js: [
      "// tokens-per-ticket CLI. Generated by `pnpm build:cli` from src/cli; don't edit by hand.",
      
      'import { createRequire as __tptRequire } from "node:module";',
      "const require = __tptRequire(import.meta.url);",
    ].join("\n"),
  },
  define: { __DEFAULT_CONFIG__: JSON.stringify(readFileSync("tokens-per-ticket.yaml", "utf8")) },
});
console.log("built .tokens-per-ticket/tpt.mjs");
